### ISSUE TITLE
Segments downloaded but not saved into downloader directory after adding and starting the stream

### ISSUE THREAD

**Issue by moutamared** [DRM-Scripts/DRMPHP#18]
Hello bud

everything was good before the latest update when i add new channel and starting it, it download the segments and decoding it, and the stream works
but after i installed the latest updated i notice that i play the channel but segments downloaded but not saved into the folder, i've tried many links and providers and nothing seems to work for me
i reinstalled the system and install the panel on fresh server, addung some channels and seems nothing to work for me and i can't solve it, because it seems the panel doesn't save the segments into the folder

Thank you so much

**Comment by DRM-Scripts** [comment]
I’ll take a look at this tomorrow. As about to push out another update tomorrow so might have missed something.

**Comment by moutamared** [comment]
thank you 
also, it seems the mpd parser doesn't works with tivify streams, when clicking on parse mpd, it does shows nothing.

**Comment by DRM-Scripts** [comment]
> thank you
> also, it seems the mpd parser doesn't works with tivify streams, when clicking on parse mpd, it does shows nothing.

Apologies on the delay, I check against the manaifest type later. The joys of certain providers just doing what they like.

**Comment by Dazzler1985** [comment]
Streams are given as error because they dont write to the /download/channelname/hls directory thats why you also cant preview.
It seems streams / hls are in /download/channelname/stream directory.

If you edit your m3u8 url to that path you can watch the stream .

So the error and not able to preview are because streams are outputted in /stream and not /hls .
